// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {main} from '../models';

export function LoadConfig():Promise<backend.Config>;

export function RunAnalyze(arg1:main.AnalyzeParams):Promise<main.AnalyzeResult>;

export function RunReview(arg1:main.ReviewParams):Promise<main.ReviewResult>;

export function SaveConfig(arg1:backend.Config):Promise<void>;

export function SelectDirectory():Promise<string>;
